var AllFunctionMapping =[{ "keyCode": "Multimedia_Fun_0", "functionType": "Multimedia", "value": "Media Player", "hid": 0, "translate": "Media Player", "code": "Multimedia_Fun_0" },
{ "keyCode": "Multimedia_Fun_1", "functionType": "Multimedia", "value": "Play/Pause", "hid": 1, "translate": "Play/Pause", "code": "Multimedia_Fun_1" },
{ "keyCode": "Multimedia_Fun_2", "functionType": "Multimedia", "value": "Next", "hid": 7, "translate": "Next", "code": "Multimedia_Fun_2" },
{ "keyCode": "Multimedia_Fun_3", "functionType": "Multimedia", "value": "Previous", "hid": 6, "translate": "Previous", "code": "Multimedia_Fun_3" },
{ "keyCode": "Multimedia_Fun_4", "functionType": "Multimedia", "value": "Stop", "hid": 5, "translate": "Stop", "code": "Multimedia_Fun_4" },
{ "keyCode": "Multimedia_Fun_5", "functionType": "Multimedia", "value": "Mute", "hid": 2, "translate": "Mute", "code": "Multimedia_Fun_5" },
{ "keyCode": "Multimedia_Fun_6", "functionType": "Multimedia", "value": "Volume up", "hid": 3, "translate": "Volume up", "code": "Multimedia_Fun_6" },
{ "keyCode": "Multimedia_Fun_7", "functionType": "Multimedia", "value": "Volume down", "hid": 4, "translate": "Volume down", "code": "Multimedia_Fun_7" },
{ "keyCode": "Multimedia_Fun_8", "functionType": "Multimedia", "value": "Next track", "hid": 7, "translate": "Next track", "code": "Multimedia_Fun_8" },
{ "keyCode": "Multimedia_Fun_9", "functionType": "Multimedia", "value": "Previou strack", "hid": 6, "translate": "Previoustrack", "code": "Multimedia_Fun_9" },
{ "keyCode": "KEYBOARD_Fun_10", "functionType": "KEYBOARD", "value": "Profilecycleup", "hid": 2, "translate": "Profilecycleup", "code": "KEYBOARD_Fun_10" },
{ "keyCode": "KEYBOARD_Fun_11", "functionType": "KEYBOARD", "value": "Profilecycledown", "hid": 1, "translate": "Profilecycledown", "code": "KEYBOARD_Fun_11" },
{ "keyCode": "KEYBOARD_Fun_12", "functionType": "KEYBOARD", "value": "Layercycleup", "hid": 4, "translate": "Layercycleup", "code": "KEYBOARD_Fun_12" },
{ "keyCode": "KEYBOARD_Fun_13", "functionType": "KEYBOARD", "value": "Layercycledown", "hid": 3, "translate": "Layercycledown", "code": "KEYBOARD_Fun_13" },


{ "keyCode": "MOUSE_Fun_14", "functionType": "MOUSE", "value": "MouseLeft", "hid": 1, "translate": "MouseLeft", "code": "MouseLeft" },
{ "keyCode": "MOUSE_Fun_15", "functionType": "MOUSE", "value": "MouseRight", "hid": 2, "translate": "MouseRight", "code": "MouseRight" },
{ "keyCode": "MOUSE_Fun_16", "functionType": "MOUSE", "value": "MouseMiddle", "hid": 3, "translate": "MouseMiddle", "code": "MouseMiddle" },

{ "keyCode": "MOUSE_Fun_14", "functionType": "MOUSE", "value": "MouseMoveUp1", "hid": 1, "translate": "MouseMoveUp1", "code": "MouseMoveUp1" },
{ "keyCode": "MOUSE_Fun_15", "functionType": "MOUSE", "value": "MouseMoveDown1", "hid": 2, "translate": "MouseMoveDown1", "code": "MouseMoveDown1" },
{ "keyCode": "MOUSE_Fun_16", "functionType": "MOUSE", "value": "MouseMoveLeft1", "hid": 3, "translate": "MouseMoveLeft1", "code": "MouseMoveLeft1" },
{ "keyCode": "MOUSE_Fun_16", "functionType": "MOUSE", "value": "MouseMoveRight1", "hid": 3, "translate": "MouseMoveRight1", "code": "MouseMoveRight1" },

{ "keyCode": "MOUSE_Fun_14", "functionType": "MOUSE", "value": "MouseMoveUp3", "hid": 1, "translate": "MouseMoveUp3", "code": "MouseMoveUp3" },
{ "keyCode": "MOUSE_Fun_15", "functionType": "MOUSE", "value": "MouseMoveDown3", "hid": 2, "translate": "MouseMoveDown3", "code": "MouseMoveDown3" },
{ "keyCode": "MOUSE_Fun_16", "functionType": "MOUSE", "value": "MouseMoveLeft3", "hid": 3, "translate": "MouseMoveLeft3", "code": "MouseMoveLeft3" },
{ "keyCode": "MOUSE_Fun_16", "functionType": "MOUSE", "value": "MouseMoveRight3", "hid": 3, "translate": "MouseMoveRight3", "code": "MouseMoveRight3" },





{ "keyCode": "MOUSE_Fun_17", "functionType": "MOUSE", "value": "Forward", "hid": 5, "translate": "Forward", "code": "MOUSE_Fun_17" },
{ "keyCode": "MOUSE_Fun_18", "functionType": "MOUSE", "value": "Back", "hid": 4, "translate": "Back", "code": "MOUSE_Fun_18" },
{ "keyCode": "MOUSE_Fun_19", "functionType": "MOUSE", "value": "Scrollup", "hid": 6, "translate": "Scrollup", "code": "MOUSE_Fun_19" },
{ "keyCode": "MOUSE_Fun_20", "functionType": "MOUSE", "value": "Scrolldown", "hid": 7, "translate": "Scrolldown", "code": "MOUSE_Fun_20" },
{ "keyCode": "MOUSE_Fun_21", "functionType": "MOUSE", "value": "Profilecycleup", "hid": 1944, "translate": "Profilecycleup", "code": "MOUSE_Fun_21" },
{ "keyCode": "MOUSE_Fun_22", "functionType": "MOUSE", "value": "Profilecycledown", "hid": 1943, "translate": "Profilecycledown", "code": "MOUSE_Fun_22" },
{ "keyCode": "MOUSE_Fun_23", "functionType": "MOUSE", "value": "Batterystatuscheck", "hid": 1942, "translate": "Batterystatuscheck", "code": "MOUSE_Fun_23" },
{ "keyCode": "LaunchProgram", "functionType": "LaunchProgram", "value": "LaunchProgram", "hid": 1941, "translate": "LaunchProgram", "code": "LaunchProgram" },
{ "keyCode": "LaunchWebsite", "functionType": "LaunchProgram", "value": "LaunchWebsite", "hid": 1940, "translate": "LaunchWebsite", "code": "LaunchWebsite" },
{ "keyCode": "Shortcuts_Fun_25", "functionType": "Shortcuts", "value": "Email", "hid": 17, "translate": "Email", "code": "Shortcuts_Fun_25" },
{ "keyCode": "Shortcuts_Fun_26", "functionType": "Shortcuts", "value": "Calculator", "hid": 16, "translate": "Calculator", "code": "Shortcuts_Fun_26" },
{ "keyCode": "Shortcuts_Fun_27", "functionType": "Shortcuts", "value": "My Computer", "hid": 15, "translate": "My Computer", "code": "Shortcuts_Fun_27" },
{ "keyCode": "Shortcuts_Fun_28", "functionType": "Shortcuts", "value": "Explorer", "hid": 15, "translate": "Explorer", "code": "Shortcuts_Fun_28" },
{ "keyCode": "Shortcuts_Fun_29", "functionType": "Shortcuts", "value": "WWW Home", "hid": 8, "translate": "WWW Home", "code": "Shortcuts_Fun_29" },
{ "keyCode": "Shortcuts_Fun_30", "functionType": "Shortcuts", "value": "WWW Refresh", "hid": 9, "translate": "WWW Refresh", "code": "Shortcuts_Fun_30" },
{ "keyCode": "Shortcuts_Fun_31", "functionType": "Shortcuts", "value": "WWW Stop", "hid": 10, "translate": "WWW Stop", "code": "Shortcuts_Fun_31" },
{ "keyCode": "Shortcuts_Fun_32", "functionType": "Shortcuts", "value": "WWW Back", "hid": 11, "translate": "WWW Back", "code": "Shortcuts_Fun_32" },
{ "keyCode": "Shortcuts_Fun_33", "functionType": "Shortcuts", "value": "WWW Forward", "hid": 12, "translate": "WWW Forward", "code": "Shortcuts_Fun_33" },
{ "keyCode": "Shortcuts_Fun_34", "functionType": "Shortcuts", "value": "WWW Search", "hid": 14, "translate": "WWW Search", "code": "Shortcuts_Fun_34" },
{ "keyCode": "Side Light", "functionType": "SideLight", "value": "Side Light", "hid": 14, "translate": "Side Light", "code": "Side Light" },
{ "keyCode": "slider", "functionType": "slider", "value": "SLIDER", "hid": 14, "translate": "slider", "code": "slider" },
{ "keyCode": "ROTARY ENCODER", "functionType": "RotaryEncoder", "value": "ROTARY ENCODER", "hid": 14, "translate": "ROTARY ENCODER", "code": "ROTARY ENCODER" },
{ "keyCode": "MacroFunction", "functionType": "MacroFunction", "value": "MacroFunction", "hid": 1923, "translate": "MacroFunction", "code": "MacroFunction" },
{ "keyCode": "ScrollWheel", "functionType": "ScrollWheel", "value": "Volume", "hid": 1922, "translate": "ScrollWheel", "code": "ScrollWheel" },
{ "keyCode": "Custom_Fnkey", "functionType": "Custom_Fnkey", "value": "Custom_Fnkey", "hid": "0x781", "translate": "FunctionLock", "code": "Custom_Fnkey" },
{ "keyCode": "FunctionLock", "functionType": "FunctionLock", "value": "FunctionLock", "hid": "0x781", "translate": "FunctionLock", "code": "FunctionLock" },
{ "keyCode": "WinLock", "functionType": "WinLock", "value": "WinLock", "hid": "0x781", "translate": "WinLock", "code": "WinLock" },

{ "keyCode": "0", "functionType": "Singlekey", "value": "Left Click", "hid": 0xB0, "hid_ModelO:": 0x01, "translate": "Left Click", "code": "0" },
{ "keyCode": "1", "functionType": "Singlekey", "value": "Scroll Click", "hid": 0xB2, "hid_ModelO:": 0x03, "translate": "Scroll Click", "code": "1" },
{ "keyCode": "2", "functionType": "Singlekey", "value": "Right Click", "hid": 0xB1, "hid_ModelO:": 0x02, "translate": "Right Click", "code": "2" },
{ "keyCode": "3", "functionType": "Singlekey", "value": "Back Key", "hid": 0xB3, "hid_ModelO": 0x02, "translate": "Back Key", "code": "3" },
{ "keyCode": "4", "functionType": "Singlekey", "value": "Forward Key", "hid": 0xB4, "hid_ModelO": 0x02, "translate": "Forward Key", "code": "4" },
{ "keyCode": "65", "functionType": "Singlekey", "value": "A", "hid": 0x04, "translate": "A", "code": "KeyA" },
{ "keyCode": "66", "functionType": "Singlekey", "value": "B", "hid": 0x05, "translate": "B", "code": "KeyB" },
{ "keyCode": "67", "functionType": "Singlekey", "value": "C", "hid": 0x06, "translate": "C", "code": "KeyC" },
{ "keyCode": "68", "functionType": "Singlekey", "value": "D", "hid": 0x07, "translate": "D", "code": "KeyD" },
{ "keyCode": "69", "functionType": "Singlekey", "value": "E", "hid": 0x08, "translate": "E", "code": "KeyE" },
{ "keyCode": "70", "functionType": "Singlekey", "value": "F", "hid": 0x09, "translate": "F", "code": "KeyF" },
{ "keyCode": "71", "functionType": "Singlekey", "value": "G", "hid": 0x0A, "translate": "G", "code": "KeyG" },
{ "keyCode": "72", "functionType": "Singlekey", "value": "H", "hid": 0x0B, "translate": "H", "code": "KeyH" },
{ "keyCode": "73", "functionType": "Singlekey", "value": "I", "hid": 0x0C, "translate": "I", "code": "KeyI" },
{ "keyCode": "74", "functionType": "Singlekey", "value": "J", "hid": 0x0D, "translate": "J", "code": "KeyJ" },
{ "keyCode": "75", "functionType": "Singlekey", "value": "K", "hid": 0x0E, "translate": "K", "code": "KeyK" },
{ "keyCode": "76", "functionType": "Singlekey", "value": "L", "hid": 0x0F, "translate": "L", "code": "KeyL" },
{ "keyCode": "77", "functionType": "Singlekey", "value": "M", "hid": 0x10, "translate": "M", "code": "KeyM" },
{ "keyCode": "78", "functionType": "Singlekey", "value": "N", "hid": 0x11, "translate": "N", "code": "KeyN" },
{ "keyCode": "79", "functionType": "Singlekey", "value": "O", "hid": 0x12, "translate": "O", "code": "KeyO" },
{ "keyCode": "80", "functionType": "Singlekey", "value": "P", "hid": 0x13, "translate": "P", "code": "KeyP" },
{ "keyCode": "81", "functionType": "Singlekey", "value": "Q", "hid": 0x14, "translate": "Q", "code": "KeyQ" },
{ "keyCode": "82", "functionType": "Singlekey", "value": "R", "hid": 0x15, "translate": "R", "code": "KeyR" },
{ "keyCode": "83", "functionType": "Singlekey", "value": "S", "hid": 0x16, "translate": "S", "code": "KeyS" },
{ "keyCode": "84", "functionType": "Singlekey", "value": "T", "hid": 0x17, "translate": "T", "code": "KeyT" },
{ "keyCode": "85", "functionType": "Singlekey", "value": "U", "hid": 0x18, "translate": "U", "code": "KeyU" },
{ "keyCode": "86", "functionType": "Singlekey", "value": "V", "hid": 0x19, "translate": "V", "code": "KeyV" },
{ "keyCode": "87", "functionType": "Singlekey", "value": "W", "hid": 0x1A, "translate": "W", "code": "KeyW" },
{ "keyCode": "88", "functionType": "Singlekey", "value": "X", "hid": 0x1B, "translate": "X", "code": "KeyX" },
{ "keyCode": "89", "functionType": "Singlekey", "value": "Y", "hid": 0x1C, "translate": "Y", "code": "KeyY" },
{ "keyCode": "90", "functionType": "Singlekey", "value": "Z", "hid": 0x1D, "translate": "Z", "code": "KeyZ" },
{ "keyCode": "48", "functionType": "Singlekey", "value": "0", "hid": 0x27, "translate": "0", "code": "Digit0" },
{ "keyCode": "49", "functionType": "Singlekey", "value": "1", "hid": 0x1E, "translate": "1", "code": "Digit1" },
{ "keyCode": "50", "functionType": "Singlekey", "value": "2", "hid": 0x1F, "translate": "2", "code": "Digit2" },
{ "keyCode": "51", "functionType": "Singlekey", "value": "3", "hid": 0x20, "translate": "3", "code": "Digit3" },
{ "keyCode": "52", "functionType": "Singlekey", "value": "4", "hid": 0x21, "translate": "4", "code": "Digit4" },
{ "keyCode": "53", "functionType": "Singlekey", "value": "5", "hid": 0x22, "translate": "5", "code": "Digit5" },
{ "keyCode": "54", "functionType": "Singlekey", "value": "6", "hid": 0x23, "translate": "6", "code": "Digit6" },
{ "keyCode": "55", "functionType": "Singlekey", "value": "7", "hid": 0x24, "translate": "7", "code": "Digit7" },
{ "keyCode": "56", "functionType": "Singlekey", "value": "8", "hid": 0x25, "translate": "8", "code": "Digit8" },
{ "keyCode": "57", "functionType": "Singlekey", "value": "9", "hid": 0x26, "translate": "9", "code": "Digit9" },
{ "keyCode": "8", "functionType": "Singlekey", "value": "Backspace", "hid": 42, "translate": "Backspace", "code": "Backspace" },
{ "keyCode": "9", "functionType": "Singlekey", "value": "Tab", "hid": 43, "translate": "Tab", "code": "Tab" },
{ "keyCode": "144", "functionType": "Singlekey", "value": "Num Lock", "hid": 83, "translate": "Num Lock", "code": "NumLock" },
{ "keyCode": "13", "functionType": "Singlekey", "value": "Enter", "hid": 40, "translate": "Enter", "code": "Enter" },
{ "keyCode": "16", "functionType": "Singlekey", "value": "Shift", "hid": 225, "translate": "Shift", "code": "ShiftRight" },
{ "keyCode": "16", "functionType": "Singlekey", "value": "Shift", "hid": 225, "translate": "Shift", "code": "ShiftLeft" },
{ "keyCode": "17", "functionType": "Singlekey", "value": "Ctrl", "hid": 224, "translate": "Ctrl", "code": "ControlLeft" },
{ "keyCode": "17", "functionType": "Singlekey", "value": "Ctrl", "hid": 224, "translate": "Ctrl", "code": "ControlRight" },
{ "keyCode": "18", "functionType": "Singlekey", "value": "Alt", "hid": 226, "translate": "Alt", "code": "AltRight" },
{ "keyCode": "18", "functionType": "Singlekey", "value": "Alt", "hid": 226, "translate": "Alt", "code": "AltLeft" },
{ "keyCode": "19", "functionType": "Singlekey", "value": "Break", "hid": 72, "translate": "Break", "code": "Pause" },
{ "keyCode": "20", "functionType": "Singlekey", "value": "CapsLock", "hid": 57, "translate": "CapsLock", "code": "CapsLock" },
{ "keyCode": "27", "functionType": "Singlekey", "value": "Esc", "hid": 41, "translate": "Esc", "code": "Escape" },
{ "keyCode": "32", "functionType": "Singlekey", "value": "Space", "hid": 44, "translate": "Space", "code": "Space" },
{ "keyCode": "33", "functionType": "Singlekey", "value": "PageUp", "hid": 75, "translate": "PageUp", "code": "PageUp" },
{ "keyCode": "34", "functionType": "Singlekey", "value": "PageDown", "hid": 78, "translate": "PageDown", "code": "PageDown" },
{ "keyCode": "35", "functionType": "Singlekey", "value": "End", "hid": 77, "translate": "End", "code": "End" },
{ "keyCode": "36", "functionType": "Singlekey", "value": "Home", "hid": 74, "translate": "Home", "code": "Home" },
{ "keyCode": "37", "functionType": "Singlekey", "value": "Left", "hid": 80, "translate": "Left", "code": "ArrowLeft" },
{ "keyCode": "38", "functionType": "Singlekey", "value": "Up", "hid": 82, "translate": "Up", "code": "ArrowUp" },
{ "keyCode": "39", "functionType": "Singlekey", "value": "Right", "hid": 79, "translate": "Right", "code": "ArrowRight" },
{ "keyCode": "40", "functionType": "Singlekey", "value": "Down", "hid": 81, "translate": "Down", "code": "ArrowDown" },
{ "keyCode": "44", "functionType": "Singlekey", "value": "PrintScreen", "hid": "0x46", "translate": "PrintScreen", "code": "PrintScreen" },
{ "keyCode": "45", "functionType": "Singlekey", "value": "Insert", "hid": 73, "translate": "Insert", "code": "Insert" },
{ "keyCode": "46", "functionType": "Singlekey", "value": "Delete", "hid": 76, "translate": "Delete", "code": "Delete" },
{ "keyCode": "91", "functionType": "Singlekey", "value": "Left Win", "hid": 227, "translate": "Left Win", "code": "MetaLeft" },
{ "keyCode": "92", "functionType": "Singlekey", "value": "Right Win", "hid": 231, "Modifier": 0x80, "translate": "Right Win", "code": "MetaRight" },
{ "keyCode": "93", "functionType": "Singlekey", "value": "Menu", "hid": 101, "translate": "Menu", "code": "ContextMenu" },
{ "keyCode": "96", "functionType": "Singlekey", "value": "0", "hid": 0x62, "translate": "Numpad0", "code": "Numpad0" },
{ "keyCode": "97", "functionType": "Singlekey", "value": "1", "hid": 0x59, "translate": "Numpad1", "code": "Numpad1" },
{ "keyCode": "98", "functionType": "Singlekey", "value": "2", "hid": 0x5a, "translate": "Numpad2", "code": "Numpad2" },
{ "keyCode": "99", "functionType": "Singlekey", "value": "3", "hid": 0x5b, "translate": "Numpad3", "code": "Numpad3" },
{ "keyCode": "100", "functionType": "Singlekey", "value": "4", "hid": 0x5c, "translate": "Numpad4", "code": "Numpad4" },
{ "keyCode": "101", "functionType": "Singlekey", "value": "5", "hid": 0x5d, "translate": "Numpad5", "code": "Numpad5" },
{ "keyCode": "102", "functionType": "Singlekey", "value": "6", "hid": 0x5e, "translate": "Numpad6", "code": "Numpad6" },
{ "keyCode": "103", "functionType": "Singlekey", "value": "7", "hid": 0x5f, "translate": "Numpad7", "code": "Numpad7" },
{ "keyCode": "104", "functionType": "Singlekey", "value": "8", "hid": 0x60, "translate": "Numpad8", "code": "Numpad8" },
{ "keyCode": "105", "functionType": "Singlekey", "value": "9", "hid": 0x61, "translate": "Numpad9", "code": "Numpad9" },
{ "keyCode": "13", "functionType": "Singlekey", "value": "Enter", "hid": 0x58, "translate": "NumpadEnter", "code": "NumpadEnter" },
{ "keyCode": "106", "functionType": "Singlekey", "value": "*", "hid": 85, "translate": "*", "code": "NumpadMultiply" },
{ "keyCode": "107", "functionType": "Singlekey", "value": "+", "hid": 87, "translate": "+", "code": "NumpadAdd" },
{ "keyCode": "109", "functionType": "Singlekey", "value": "-", "hid": 86, "translate": "-", "code": "NumpadSubtract" },
{ "keyCode": "110", "functionType": "Singlekey", "value": ".", "hid": 0x63, "translate": ".", "code": "NumpadDecimal" },
{ "keyCode": "111", "functionType": "Singlekey", "value": "/", "hid": 84, "translate": "/", "code": "NumpadDivide" },
{ "keyCode": "112", "functionType": "Singlekey", "value": "F1", "hid": 0x3A, "translate": "F1", "code": "F1" },
{ "keyCode": "113", "functionType": "Singlekey", "value": "F2", "hid": 0x3B, "translate": "F2", "code": "F2" },
{ "keyCode": "114", "functionType": "Singlekey", "value": "F3", "hid": 0x3C, "translate": "F3", "code": "F3" },
{ "keyCode": "115", "functionType": "Singlekey", "value": "F4", "hid": 0x3D, "translate": "F4", "code": "F4" },
{ "keyCode": "116", "functionType": "Singlekey", "value": "F5", "hid": 0x3E, "translate": "F5", "code": "F5" },
{ "keyCode": "117", "functionType": "Singlekey", "value": "F6", "hid": 0x3F, "translate": "F6", "code": "F6" },
{ "keyCode": "118", "functionType": "Singlekey", "value": "F7", "hid": 0x40, "translate": "F7", "code": "F7" },
{ "keyCode": "119", "functionType": "Singlekey", "value": "F8", "hid": 0x41, "translate": "F8", "code": "F8" },
{ "keyCode": "120", "functionType": "Singlekey", "value": "F9", "hid": 0x42, "translate": "F9", "code": "F9" },
{ "keyCode": "121", "functionType": "Singlekey", "value": "F10", "hid": 0x43, "translate": "F10", "code": "F10" },
{ "keyCode": "122", "functionType": "Singlekey", "value": "F11", "hid": 0x44, "translate": "F11", "code": "F11" },
{ "keyCode": "123", "functionType": "Singlekey", "value": "F12", "hid": 0x45, "translate": "F12", "code": "F12" },
{ "keyCode": "145", "functionType": "Singlekey", "value": "Scroll Lock", "hid": 71, "translate": "Scroll Lock", "code": "ScrollLock" },
{ "keyCode": "186", "functionType": "Singlekey", "value": ";", "hid": 51, "translate": ";", "code": "Semicolon" },
{ "keyCode": "187", "functionType": "Singlekey", "value": "=", "hid": 46, "translate": "=", "code": "Equal" },
{ "keyCode": "188", "functionType": "Singlekey", "value": ",", "hid": 54, "translate": ",", "code": "Comma" },
{ "keyCode": "189", "functionType": "Singlekey", "value": "-", "hid": 45, "translate": "-", "code": "Minus" },
{ "keyCode": "190", "functionType": "Singlekey", "value": "dot", "hid": 55, "translate": "dot", "code": "Period" },
{ "keyCode": "191", "functionType": "Singlekey", "value": "/", "hid": 56, "translate": "/", "code": "Slash" },
{ "keyCode": "192", "functionType": "Singlekey", "value": "~", "hid": 53, "translate": "~", "code": "Backquote" },
{ "keyCode": "219", "functionType": "Singlekey", "value": "[", "hid": 47, "translate": "[", "code": "BracketLeft" },
{ "keyCode": "220", "functionType": "Singlekey", "value": "|", "hid": 49, "translate": "|", "code": "Backslash" },
{ "keyCode": "226", "functionType": "Singlekey", "value": "\\", "hid": 49, "translate": "IntlBackslash", "code": "IntlBackslash" },
{ "keyCode": "221", "functionType": "Singlekey", "value": "]", "hid": 48, "translate": "]", "code": "BracketRight" },
{ "keyCode": "222", "functionType": "Singlekey", "value": "'", "hid": 52, "translate": "'", "code": "Quote" }]
